### ISSUE TITLE
Make parser a stand-alone package

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydra-openapi-parser#5]
The parser should be usable on its own outside of hydrus.
We need to find the cleanest way of porting the history in this repository and then build an interface (CLI) to make the parser usable as a stand-alone or library installable via `pip` from hydrus.

**Comment by shravandoda** [comment]
But as @xadahiya stated openAPI Parser imports hydrus as a dependency

**Comment by chrizandr** [comment]
> But as @xadahiya stated openAPI Parser imports hydrus as a dependency

As mentioned here https://github.com/HTTP-APIs/hydra-openapi-parser/pull/2#issuecomment-452629207

The parser only uses the tools in hydraspec. These are not strictly for `hydrus` only, you can use these tools as a separate library in itself. The idea now is to be able to use hydrus.hydraspec as a separate library.

@Mec-iS I also think that we should consider a repo for parsers in general, rather than having one for every different kind of parser. I remember writing one for OWL vocabularies as well, which is there in `hydrus.hydraspec.legacy`. Maybe have a repo for parsers in general? We can add more parsers to this package as we develop them.

**Comment by de-sh** [comment]
> you can use these tools as a separate library in itself.

@chrizandr so, is hydra.hydraspec maintained as a separate repo/package? but metadata comes from hydrus namespace... so this is not really a possibility is it?

**Comment by shravandoda** [comment]
So how are we going to proceed? Do we make another repo for hydraspec and use it in hydrus and other parsers?

**Comment by Mec-iS** [comment]
in theory everything should be modular. should adapt this principle to practices.

i would create a repo `python-hydra-core` for hydraspecs.

**Comment by Mec-iS** [comment]
I moved the related code in this repo df27d3016e218734b0df4fbaadc26390e753b0b0

**Comment by Mec-iS** [comment]
completed eea6a3e
